# Generated by Django 5.2 on 2025-04-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ProductID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ProductType', models.CharField(max_length=100)),
                ('ProductSize', models.CharField(max_length=100)),
                ('ProductPrice', models.CharField(max_length=100)),
            ],
        ),
    ]
