# Generated by Django 5.2 on 2025-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ProductStock',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
